org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.23
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=zoomify
mod_name=Zoomify++
mod_license=LGPLv3
mod_version=1.2.0
mod_group_id=id.patchedpixel.zoomify
mod_authors=isxander
mod_description=A zoom mod with infinite customizability.